name: Master Workflow

on:
  push:
    branches:
      - "main"

  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: func-cos-app-dev
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "."

jobs:
  build:
    name: 🧪 Build and Test
    runs-on: [kubernetes]
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2

      - name: Before Script
        id: script
        run: |
          python3 -V
          pip install --upgrade pip
          pip install -r requirements.txt
